# Generated by Django 4.1.6 on 2023-02-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='DateOFJoining',
            new_name='DateOfJoining',
        ),
    ]
